### ISSUE TITLE
Ошибка в README

### ISSUE THREAD

**Issue by OnlyMalinka** [XNicON/hassio-salutespeech#1]
В примере заполнения configuration.yaml переменная rate указано как int, хотя она должна быть string. При добавлении кавычек все работает исправно.
Вот ошибка из логов: ERROR (MainThread) [homeassistant.config] Invalid config for 'tts' from integration 'sbertts' at configuration.yaml, line 24: value must be one of ['24000', '8000'] for dictionary value 'rate', got 24000

**Comment by XNicON** [comment]
Поправил, спасибо!
